CREATE TABLE IF NOT EXISTS `drs_vehicle_contract_operations` (
    `operation_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `operation_type` VARCHAR(32) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `step` VARCHAR(48) NOT NULL,
    `active_plate` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `plate` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `vehicle_row_id` VARCHAR(64) NULL,
    `actor_identifier` VARCHAR(80) NOT NULL,
    `counterparty_identifier` VARCHAR(80) NULL,
    `job` VARCHAR(50) NULL,
    `price` INT UNSIGNED NOT NULL DEFAULT 0,
    `payment_account` VARCHAR(32) NOT NULL DEFAULT 'money',
    `item_name` VARCHAR(64) NOT NULL,
    `item_removed` TINYINT(1) NOT NULL DEFAULT 0,
    `money_debited` TINYINT(1) NOT NULL DEFAULT 0,
    `ownership_changed` TINYINT(1) NOT NULL DEFAULT 0,
    `money_credited` TINYINT(1) NOT NULL DEFAULT 0,
    `keys_updated` TINYINT(1) NOT NULL DEFAULT 0,
    `compensated` TINYINT(1) NOT NULL DEFAULT 0,
    `failure_text` VARCHAR(1000) NULL,
    `created_at` BIGINT UNSIGNED NOT NULL,
    `updated_at` BIGINT UNSIGNED NOT NULL,
    `completed_at` BIGINT UNSIGNED NULL,
    PRIMARY KEY (`operation_id`),
    UNIQUE KEY `ux_drs_vehicle_contract_active_plate` (`active_plate`),
    KEY `idx_drs_vehicle_contract_status_updated` (`status`, `updated_at`),
    KEY `idx_drs_vehicle_contract_plate_created` (`plate`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
